name: Shuttle deployment

on:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  fmt-lint:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.10.1

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --verbose --all-targets --all-features -- -D warnings

  tests:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.10.1

      - name: Tests
        run: cargo test --verbose --all-targets --no-fail-fast --release

  deploy:
    needs: [fmt-lint, tests]

    runs-on: ubuntu-latest

    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          project-id: ${{ secrets.SHUTTLE_PROJECT_ID }}
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
